export const SUBJECT_NAMES = {
  ART: "Arte",
  BIO: "Biologia",
  EDF: "Educação Física",
  FIL: "Filosofia",
  FIS: "Física",
  GEO: "Geografia",
  HIS: "História",
  ESP: "Língua Estrangeira Moderna - Espanhol",
  ING: "Língua Estrangeira Moderna - Inglês",
  POR: "Língua Portuguesa",
  MAT: "Matemática",
  PD1: "Projeto Interdisciplinar I",
  PD2: "Projeto Interdisciplinar II",
  PD3: "Projeto Interdisciplinar III",
  QUI: "Química",
  SOC: "Sociologia",
};

export const SUBJECT_ABBREVIATIONS = {
  Arte: "ART",
  Biologia: "BIO",
  "Educação Física": "EDF",
  Filosofia: "FIL",
  Física: "FIS",
  Geografia: "GEO",
  História: "HIS",
  "Língua Estrangeira Moderna - Espanhol": "ESP",
  "Língua Estrangeira Moderna - Inglês": "ING",
  "Língua Portuguesa": "POR",
  Matemática: "MAT",
  "Projeto Interdisciplinar I": "PD1",
  "Projeto Interdisciplinar II": "PD2",
  "Projeto Interdisciplinar III": "PD3",
  Química: "QUI",
  Sociologia: "SOC",
};

export const GROUP_NAMES = [
  "Amazônia",
  "Andiroba",
  "Angelim",
  "Arara-azul",
  "Araucária",
  "Ariranha",
  "Baru",
  "Braúna",
  "Bromélia",
  "Buriti",
  "Caatinga",
  "Caixeta",
  "Campos",
  "Castanheira",
  "Cedro",
  "Cerejeira",
  "Cerrado",
  "Chauá",
  "Deserto",
  "Florestas",
  "Garapeira",
  "Gato-maracajá",
  "Gavião-real",
  "Graviola",
  "Imbuia",
  "Jacarandá",
  "Jacutinga",
  "Jatobá",
  "Jenipapo",
  "Jequitibá",
  "Lobo-guará",
  "Mangaba",
  "Mata Atlântica",
  "Mico-leão-dourado",
  "Mogno",
  "Muriqui",
  "Onça-pintada",
  "Pampas",
  "Pantanal",
  "Pau-Brasil",
  "Pequi",
  "Sagui",
  "Savana",
  "Taiga",
  "Tamanduá-bandeira",
  "Tartaruga-gigante",
  "Tatu-bola",
  "Tucuxi",
  "Tundra",
  "Uacari",
];
